org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.92
neo_version_range=[21.1.92,)
loader_version_range=[1,)

## Mod Properties
mod_id=quantum_quarry
mod_name=Quantum Quarry
mod_license=GPL-3.0
mod_version=1.0.0
mod_group_id=com.quantum.quantum_quarry
mod_authors=DeadmanLabs, SuperScary
mod_description=Port of the Quantum Quarry from Extra Utilities 2 to Minecraft 1.21+
